server:
  port: 8443
  ssl:
    key-store: school_security_application_keystore.jks
    key-store-password: youd_like_to_know_right #replace with real pw
    keyAlias: school_security_certificate
    key-store-type: JKS
    key-password: youd_like_to_know_right #replace with real pw
spring:
  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/securityapp
    username: securityapp
    password:
  jpa:
    hibernate:
      ddl-auto: update
securityapp:
  system-command:
    command-name: # specify command to execute

logging:
  file: /var/log/m183-security-app.log
  level:
    root: INFO
    org:
      springframework:
        web: INFO
    hibernate: ERROR